export const PROJECTS = [
  {
    num: "01",
    label: "FEATURED",
    icon: "💊",
    featured: true,
    title: "Online Pharmacy Management System",
    desc: "Full-stack pharmacy platform with role-based access, Redis-cached cart, and Kafka-powered order notifications.",
    longDesc:
      "A comprehensive pharmacy management solution that serves three distinct user roles: Admin, Pharmacist, and Customer. The system handles inventory management, prescription processing, order fulfillment, and real-time notifications. Built with scalability in mind, it leverages Redis caching to reduce cart response times by 60% and Kafka for reliable event-driven communication between services.",
    achievements: [
      "Role-based access for Admin, Pharmacist & Customer via Spring Security",
      "Redis caching layer cutting cart response time significantly",
      "Kafka event-driven notifications for order & inventory updates",
      "JWT + OAuth2 dual authentication for secure sessions",
    ],
    tags: [
      { label: "Spring Boot", cls: "java" },
      { label: "Spring Security", cls: "java" },
      { label: "React", cls: "react" },
      { label: "MySQL", cls: "db" },
      { label: "Redis", cls: "db" },
      { label: "Kafka", cls: "other" },
      { label: "JWT/OAuth2", cls: "sec" },
    ],
    link: "https://github.com/ArbindDas/PharmaFlow",
    demo: "https://pharmaflow-demo.vercel.app",
    stack: [
      {
        label: "React UI",
        bg: "rgba(56,189,248,0.1)",
        color: "#38bdf8",
        border: "rgba(56,189,248,0.22)",
      },
      {
        label: "Spring Boot",
        bg: "rgba(245,158,11,0.1)",
        color: "#f59e0b",
        border: "rgba(245,158,11,0.22)",
      },
      {
        label: "MySQL + Redis",
        bg: "rgba(52,211,153,0.1)",
        color: "#34d399",
        border: "rgba(52,211,153,0.22)",
      },
      {
        label: "Kafka · JWT",
        bg: "rgba(129,140,248,0.1)",
        color: "#818cf8",
        border: "rgba(129,140,248,0.22)",
      },
    ],
    architecture: [
      "Monolithic architecture",
      "Event-driven communication via Kafka",
      "Redis for session management & caching",
      "MySQL with JPA/Hibernate for persistence",
      "React frontend with Tailwind CSS",
    ],
  },
  {
    num: "02",
    label: "ONGOING",
    icon: "⚙️",
    ongoing: true,
    title: "CommerceEngine",
    desc: "Core orchestration microservice managing e-commerce business logic — order processing, pricing, inventory coordination.",
    longDesc:
      "A robust microservice that serves as the brain of an e-commerce platform, orchestrating complex business workflows including order validation, pricing rule application, inventory checks, and payment processing coordination. Designed for high-throughput scenarios with asynchronous processing and fault tolerance.",
    achievements: [
      "Orchestrates order lifecycle, pricing rules & inventory sync across services",
      "Microservice architecture with clean service-to-service communication",
      "Scalable design for high-throughput e-commerce operations",
    ],
    tags: [
      { label: "Spring Boot", cls: "java" },
      { label: "Microservices", cls: "java" },
      { label: "Kafka", cls: "other" },
      { label: "Docker", cls: "other" },
      { label: "MySQL", cls: "db" },
    ],
    link: "https://github.com/ArbindDas/CommerceEngine",
    architecture: [
      "RESTful API design with Spring Web",
      "Kafka for async processing",
      "JPA with MySQL for data persistence",
      "Docker containerization",
      "Circuit breaker pattern with Resilience4j",
    ],
  },
  {
    num: "03",
    label: "BACKEND",
    icon: "🧩",
    title: "Quiz Microservices",
    desc: "Backend microservices with API Gateway, Eureka Service Registry, and decoupled question/quiz services.",
    longDesc:
      "A distributed system for quiz management built with Spring Cloud. Features service discovery via Eureka, centralized API Gateway routing, and completely decoupled services that can scale independently. Perfect for understanding microservices architecture patterns.",
    achievements: [
      "API Gateway handling routing across all services",
      "Eureka Service Registry for dynamic service discovery",
      "Decoupled services for independent scaling",
    ],
    tags: [
      { label: "Spring Boot", cls: "java" },
      { label: "API Gateway", cls: "java" },
      { label: "Eureka", cls: "other" },
      { label: "REST APIs", cls: "java" },
    ],
    link: "https://github.com/ArbindDas/quiz-microservices",
    architecture: [
      "Spring Cloud Gateway for routing",
      "Netflix Eureka for service discovery",
      "REST APIs between services",
      "Centralized configuration",
    ],
  },
  {
    num: "04",
    label: "FULL STACK",
    icon: "📚",
    title: "Online Book Store",
    desc: "E-commerce platform with React frontend, real-time Firebase backend, and seamless shopping UX.",
    longDesc:
      "A modern book e-commerce platform featuring real-time inventory updates, secure authentication, and a smooth checkout experience. Leverages Firebase's real-time capabilities for instant catalog updates across all connected clients.",
    achievements: [
      "Real-time Firestore syncing for instant catalog updates",
      "Firebase Auth for secure sign-up and login",
      "Responsive cart and checkout flow",
    ],
    tags: [
      { label: "React", cls: "react" },
      { label: "Firebase", cls: "other" },
      { label: "Firestore", cls: "db" },
      { label: "Auth", cls: "sec" },
    ],
    link: "https://github.com/ArbindDas/online-book-stores",
    demo: "https://bookstore-demo.vercel.app",
    architecture: [
      "React with Context API for state",
      "Firebase Authentication",
      "Cloud Firestore database",
      "Real-time subscriptions",
      "Responsive CSS modules",
    ],
  },
  {
    num: "05",
    label: "BACKEND",
    icon: "👥",
    title: "StaffEntryApp",
    desc: "Staff record management with full CRUD, validation, and clean REST API design.",
    longDesc:
      "A comprehensive staff management system providing complete CRUD operations with robust server-side validation. Features clean RESTful endpoints, comprehensive error handling, and MongoDB persistence for flexible data modeling.",
    achievements: [
      "Full CRUD: username, address, phone, salary, entry date",
      "Server-side validation ensuring data integrity",
      "Clean REST design for easy frontend integration",
    ],
    tags: [
      { label: "Spring Boot", cls: "java" },
      { label: "REST API", cls: "java" },
      { label: "Validation", cls: "sec" },
      { label: "MongoDB", cls: "db" },
    ],
    link: "https://github.com/ArbindDas/StaffEntryApp",
    architecture: [
      "Spring Boot REST controllers",
      "MongoDB with Spring Data",
      "Bean Validation API",
      "Exception handling with @ControllerAdvice",
      "DTO pattern for data transfer",
    ],
  },
  {
    num: "06",
    label: "BACKEND",
    icon: "📔",
    title: "Daily Log App",
    desc: "Secure journaling with sentiment analysis, CRUD, and admin/user role separation.",
    longDesc:
      "A privacy-focused journaling application with built-in sentiment analysis to track emotional patterns over time. Features robust security with OAuth2 + JWT, role-based access control, and automatic timestamp tracking for all entries.",
    achievements: [
      "Sentiment analysis on every entry with mood tracking",
      "OAuth2 + JWT with role-based access",
      "Auto-timestamps: created & updated tracking",
    ],
    tags: [
      { label: "Spring Boot", cls: "java" },
      { label: "Redis", cls: "db" },
      { label: "MySQL", cls: "db" },
      { label: "OAuth2+JWT", cls: "sec" },
    ],
    link: "https://github.com/ArbindDas/daily-log-app",
    architecture: [
      "Spring Security with OAuth2",
      "JWT token authentication",
      "Redis caching for improved API performance",
      "MySQL for persistent storage",
      "Sentiment analysis integration",
    ],
  },
  {
  num: "07",
  label: "JavaScript",
  icon: "🧩",
  title: "JS Playground – Mini Projects Collection",
  desc: "A collection of multiple HTML, CSS, and JavaScript projects demonstrating core web development concepts.",
  longDesc:
    "JS Playground is a repository containing multiple front-end projects built using HTML, CSS, and vanilla JavaScript. It includes interactive mini-applications designed to practice DOM manipulation, events, UI design, and JavaScript fundamentals. The repository helps beginners understand real-world implementations while providing reusable components and clean project structures.",
  achievements: [
    "Built 8+ interactive JavaScript mini projects",
    "Demonstrates DOM manipulation and event handling",
    "Clean project structure for learning and experimentation",
  ],
  tags: [
    { label: "JavaScript", cls: "react" },
    { label: "HTML", cls: "other" },
    { label: "CSS", cls: "other" },
  ],
  link: "https://github.com/ArbindDas/js-playground",
  demo: "https://github.com/ArbindDas/js-playground",
  architecture: [
    "Vanilla JavaScript DOM manipulation",
    "Event-driven UI interactions",
    "Modular mini project structure",
    "Responsive layouts using CSS",
    "Beginner-friendly code organization",
  ],
},
 
  {
    num: "08",
    label: "WEB APP",
    icon: "✅",
    title: "To-Do List App",
    desc: "Task manager with Spring Security, Thymeleaf templates, email sharing, and PDF export.",
    longDesc:
      "A full-featured task management application with secure user authentication, email sharing capabilities, and PDF export functionality. Built with Spring Boot and Thymeleaf for server-side rendering, demonstrating traditional web application patterns.",
    achievements: [
      "Spring Security sign-up/login for secure access",
      "Full task CRUD with all required fields",
      "Email sharing & PDF export for offline access",
    ],
    tags: [
      { label: "Spring Boot", cls: "java" },
      { label: "Thymeleaf", cls: "java" },
      { label: "Spring Security", cls: "sec" },
      { label: "MySQL", cls: "db" },
    ],
    link: "https://github.com/ArbindDas/To_Do_List",
    architecture: [
      "Spring MVC with Thymeleaf",
      "Spring Security for auth",
      "MySQL database",
      "PDF generation with iText",
      "Email service integration",
    ],
  },

  {
  num: "09",
  label: "FULL STACK",
  icon: "🤖",
  featured: true,
  title: "AI Document Assistant — RAG Multi-Agent System",
  desc: "RAG pipeline with multi-agent orchestration, semantic search, and LLM-powered document Q&A.",
  longDesc:
    "A full-stack AI document assistant that ingests documents, generates embeddings using Pinecone, and retrieves semantically relevant content for LLM responses. The system uses a multi-agent architecture where agents independently handle parsing, query routing, and response synthesis. Integrated with OpenAI API for LLM inference and Redis for caching to reduce latency and redundant API calls. Built for scalability and efficient knowledge retrieval.",
  achievements: [
    "RAG pipeline with Spring AI and Pinecone vector database",
    "Multi-agent architecture for document parsing, query routing, and response synthesis",
    "OpenAI API integration for LLM-powered answers",
    "Redis caching to reduce API calls and improve latency",
    "Dockerized full-stack deployment with Spring Boot backend",
  ],
  tags: [
    { label: "Spring Boot", cls: "java" },
    { label: "Spring AI", cls: "java" },
    { label: "React", cls: "react" },
    { label: "Redis", cls: "db" },
    { label: "Pinecone", cls: "db" },
    { label: "Docker", cls: "other" },
    { label: "RAG", cls: "other" },
    { label: "OpenAI API", cls: "other" },
  ],
  link: "https://github.com/ArbindDas/spring-ai-rag-document-assistant",
  demo: null,
  stack: [
    {
      label: "React UI",
      bg: "rgba(56,189,248,0.1)",
      color: "#38bdf8",
      border: "rgba(56,189,248,0.22)",
    },
    {
      label: "Spring Boot",
      bg: "rgba(245,158,11,0.1)",
      color: "#f59e0b",
      border: "rgba(245,158,11,0.22)",
    },
    {
      label: "Redis + Pinecone",
      bg: "rgba(52,211,153,0.1)",
      color: "#34d399",
      border: "rgba(52,211,153,0.22)",
    },
    {
      label: "OpenAI API · RAG",
      bg: "rgba(129,140,248,0.1)",
      color: "#818cf8",
      border: "rgba(129,140,248,0.22)",
    },
  ],
  architecture: [
    "Multi-agent system for independent task handling",
    "RAG pipeline: document ingestion → embedding → semantic search",
    "Spring Boot services coordinating agents",
    "Redis caching for frequent queries",
    "OpenAI API integration for LLM inference",
    "Dockerized deployment for portability",
  ],
}
];
