export const SKILLS = [
  {
    icon: "☕",
    title: "Core Java",
    badge: "PRIMARY",
    featured: true,
    type: "bars",
    items: [
      { name: "Core Java & OOP", pct: 95 },
      { name: "Spring Boot", pct: 90 },
      { name: "Spring Security", pct: 85 },
      { name: "Hibernate / JPA", pct: 85 },
    ],
  },
  {
    icon: "🗄️",
    title: "Databases",
    badge: "DATA",
    type: "bars",
    items: [
      { name: "MySQL", pct: 88 },
      { name: "Redis", pct: 78 },
      { name: "MongoDB", pct: 75 },
      { name: "PostgreSQL", pct: 70 },
    ],
  },
  {
    icon: "⚙️",
    title: "Java Features",
    badge: "EXPERT",
    type: "tags",
    tags: [
      "Streams API",
      "Lambdas",
      "Optional",
      "Records",
      "Sealed Classes",
      "ExecutorService",
      "CompletableFuture",
      "Design Patterns",
      "Generics",
      "Concurrency",
    ],
  },
  {
    icon: "🌐",
    title: "Frontend & DevOps",
    badge: "FULL-STACK",
    type: "tags",
    tags: [
      "React",
      "Javascript",
      "Tailwind CSS",
      "Three.js",
      "Docker",
      "Kafka",
      "Git",
      "AWS",
      "OAuth2 / JWT",
      "REST APIs",
    ],
  },
];
